name: "Garnet Runtime Security"
description: "Protect your workflows with real-time runtime security monitoring"
branding:
  icon: "shield"
  color: "blue"
inputs:
  api_token:
    description: "Garnet API token"
    required: true
  api_url:
    description: "Garnet API URL"
    required: false
    default: "https://api.garnet.ai"
  garnetctl_version:
    description: "Garnet CLI version (1.2.3, or 'latest')"
    required: false
    default: "latest"
  jibril_version:
    description: "Jibril version (1.2.3, or 0.0)"
    required: false
    default: "0.0"
  profiler_4fun:
    description: "Enable profiler 4 fun mode"
    required: false
    default: "false"
  debug:
    description: "Enable debug mode"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  post-if: "always()"
