name: 'GarnetAI'
description: 'Runs the Jibril security scanner for runtime threat detection'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_token:
    description: 'API token for GarnetAI service'
    required: true
  api_url:
    description: 'API URL for GarnetAI service'
    required: false
    default: 'https://api.garnet.ai'
  version:
    description: 'Docker image version to use'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'ghcr.io/garnet-org/action:latest'
  env:
    GARNETAI_API_TOKEN: ${{ inputs.api_token }}
    GARNETAI_API_URL: ${{ inputs.api_url }}
    VERSION: ${{ inputs.version }}
