name: "GarnetAI"
description: "Runs the Jibril security scanner for runtime threat detection"
branding:
  icon: "shield"
  color: "blue"

inputs:
  api_token:
    description: "Garnet API token"
    required: true
  api_url:
    description: "Garnet API URL"
    required: false
    default: "https://api.garnet.ai"
  garnetctl_version:
    description: "Garnet CLI version (1.2.3, or 'latest')"
    required: false
    default: "latest"
  jibril_version:
    description: "Jibril version (1.2.3, or 0.0)"
    required: false
    default: "2.9.1"
  debug:
    description: "Enable debug mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run GarnetAI Security Scanner
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/action.sh"

        export GITHUB_JOB="${{ github.job }}"
        export GITHUB_RUN_ID="${{ github.run_id }}"
        export GITHUB_WORKFLOW="${{ github.workflow }}"
        export GITHUB_REPOSITORY="${{ github.repository }}"
        export GITHUB_REPOSITORY_ID="${{ github.repository_id }}"
        export GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}"
        export GITHUB_REPOSITORY_OWNER_ID="${{ github.repository_owner_id }}"
        export GITHUB_EVENT_NAME="${{ github.event_name }}"
        export GITHUB_REF="${{ github.ref }}"
        export GITHUB_SHA="${{ github.sha }}"
        export GITHUB_ACTOR="${{ github.actor }}"
        export RUNNER_OS="${{ runner.os }}"
        export RUNNER_ARCH="${{ runner.arch }}"
        export GITHUB_ACTION_PATH="${{ github.action_path }}"

        sudo -E "${{ github.action_path }}/scripts/action.sh" \
          "${{ inputs.api_token }}" \
          "${{ inputs.api_url }}" \
          "${{ inputs.garnetctl_version }}" \
          "${{ inputs.jibril_version }}" \
          "${{ inputs.debug }}"
