name: 'GarnetAI'
description: 'Runs the Jibril security scanner for runtime threat detection'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_token:
    description: 'API token for GarnetAI service'
    required: true
  api_url:
    description: 'API URL for GarnetAI service'
    required: false
    default: 'https://api.garnet.ai'
  garnetctl_version:
    description: 'Version of garnetctl CLI to download (without v prefix)'
    required: false
    default: 'latest'
  jibril_version:
    description: 'Jibril release version for the daemon (without v prefix)'
    required: false
    default: '2.6.10'
  debug:
    description: 'Enable detailed debug output'
    required: false
    default: 'false'
  continue_on_error:
    description: 'Continue execution even if errors occur (logs errors but does not fail the action)'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Run GarnetAI Security Scanner
      shell: bash
      run: |
        # Make script executable and run it
        chmod +x "${{ github.action_path }}/scripts/run-security-scanner.sh"
        
        # Export GitHub environment variables so the script can access them
        export GITHUB_JOB="${{ github.job }}"
        export GITHUB_RUN_ID="${{ github.run_id }}"
        export GITHUB_WORKFLOW="${{ github.workflow }}"
        export GITHUB_REPOSITORY="${{ github.repository }}"
        export GITHUB_REPOSITORY_ID="${{ github.repository_id }}"
        export GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}"
        export GITHUB_REPOSITORY_OWNER_ID="${{ github.repository_owner_id }}"
        export GITHUB_EVENT_NAME="${{ github.event_name }}"
        export GITHUB_REF="${{ github.ref }}"
        export GITHUB_SHA="${{ github.sha }}"
        export GITHUB_ACTOR="${{ github.actor }}"
        export RUNNER_OS="${{ runner.os }}"
        export RUNNER_ARCH="${{ runner.arch }}"
        export GITHUB_ACTION_PATH="${{ github.action_path }}"
        
        # Run the unified script with all parameters
        sudo -E "${{ github.action_path }}/scripts/run-security-scanner.sh" \
          "${{ inputs.api_token }}" \
          "${{ inputs.api_url }}" \
          "${{ inputs.garnetctl_version }}" \
          "${{ inputs.jibril_version }}" \
          "${{ inputs.debug }}" \
          "${{ inputs.continue_on_error }}"
