# Example: run Garnet Runtime Security (Jibril) in your repository.
#
# This file is for reference only — it is not used by this repo.
# Copy it to your repo's .github/workflows/ (e.g. garnet-security.yaml).
#
# Setup:
#   1. Add your Garnet API token as a repository secret named GARNET_API_TOKEN.
#   2. Optionally set api_url, garnetctl_version, jibril_version, or debug (see below).
#
# The action runs a main step (install + start Jibril) and a post step (stop Jibril
# and append the security profile to the job summary). Use a release tag or @main.

name: Garnet Runtime Security (example)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security:
    name: Garnet Jibril
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Garnet Runtime Security
        uses: garnet-org/action@v0   # or @main, or a release tag e.g. @v1.0.0
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
          # Optional (defaults shown):
          # api_url: "https://api.garnet.ai"
          # garnetctl_version: "latest"
          # jibril_version: "0.0"
          # debug: "false"
