#!/bin/bash
set -euo pipefail

#
# Inputs (positional) from action.yaml.
#

API_TOKEN=${1:-""}
API_URL=${2:-"https://api.garnet.ai"}
GARNETCTL_VERSION=${3:-"latest"}
JIBRIL_VERSION=${4:-"0.0"}
DEBUG=${5:-"false"}

if [ "$DEBUG" = "true" ]; then
	set -x
fi

#
# Global variables and defaults.
#

INSTPATH="/usr/local/bin"

TOKEN=$API_TOKEN
API=$API_URL

GARNETVER=$GARNETCTL_VERSION
JIBRILVER=$JIBRIL_VERSION

ARCH=$(uname -m)
OS=$(uname -s)

#
# Sanity checks.
#

if [ -z "$TOKEN" ]; then
	echo "API token is required"
	exit 1
fi

case "$OS" in
Linux)
	GARNET_OS="linux"
	;;
Darwin)
	GARNET_OS="darwin"
	;;
*)
	echo "Unsupported OS: $OS"
	exit 1
	;;
esac

case "$ARCH" in
x86_64)
	ALTARCH="x86_64"
	;;
aarch64 | arm64)
	ALTARCH="arm64"
	;;
*)
	echo "Unsupported architecture: $ARCH"
	exit 1
	;;
esac

if [[ "$GARNETVER" != "latest" && "$GARNETVER" != v* ]]; then
	GARNETVER="v$GARNETVER"
fi

if [[ "$JIBRILVER" != v* ]]; then
	JIBRILVER="v$JIBRILVER"
fi

#
# Main script execution.
#

echo "API server: $API"
echo "Garnet Control Version: $GARNETVER"
echo "Jibril Version: $JIBRILVER"

#### Download.

# Garnet Control.

PREFIX="https://github.com/garnet-org/garnetctl-releases/releases/"
URL="$PREFIX/download/$GARNETVER/garnetctl_${GARNET_OS}_${ALTARCH}.tar.gz"

if [ "$GARNETVER" = "latest" ]; then
	URL="$PREFIX/latest/download/garnetctl_${GARNET_OS}_${ALTARCH}.tar.gz"
fi

echo "Downloading garnetctl: $URL"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT
curl -sL "$URL" | tar -xz -C "$TMP_DIR"

if [[ -f "$TMP_DIR/garnetctl" ]]; then
	sudo mv "$TMP_DIR/garnetctl" $INSTPATH/garnetctl
	sudo chmod +x $INSTPATH/garnetctl
else
	echo "Failed to download garnetctl binary"
	exit 1
fi

# Jibril.

URL="https://github.com/garnet-org/jibril-releases/releases/download/$JIBRILVER/jibril"

echo "Downloading jibril: $URL"

sudo curl -sL -o $INSTPATH/jibril "$URL"
sudo chmod +x $INSTPATH/jibril

#### Configure.

echo "Configuring garnetctl"

$INSTPATH/garnetctl config set-baseurl "$API"
$INSTPATH/garnetctl config set-token "$TOKEN"

# Context.

echo "Creating github context"

VERSION=$("$INSTPATH/garnetctl" version | grep -oP 'Version: \K[^,]+')

RUNNER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
RUNNER_IP=${RUNNER_IP:-127.0.0.1}

if [ -f /etc/machine-id ]; then
	SYSTEM_MACHINE_ID=$(cat /etc/machine-id)
elif [ -f /var/lib/dbus/machine-id ]; then
	SYSTEM_MACHINE_ID=$(cat /var/lib/dbus/machine-id)
else
	SYSTEM_MACHINE_ID=$(hostname)
fi

MACHINE_ID="$SYSTEM_MACHINE_ID"
HOSTNAME="$(hostname)-${GITHUB_RUN_ID:-}-${GITHUB_JOB:-}"

cat >"$TMP_DIR/github-context.json" <<EOF
{
  "job": "${GITHUB_JOB:-}",
  "run_id": "${GITHUB_RUN_ID:-}",
  "workflow": "${GITHUB_WORKFLOW:-}",
  "repository": "${GITHUB_REPOSITORY:-}",
  "repository_id": "${GITHUB_REPOSITORY_ID:-}",
  "repository_owner": "${GITHUB_REPOSITORY_OWNER:-}",
  "repository_owner_id": "${GITHUB_REPOSITORY_OWNER_ID:-}",
  "event_name": "${GITHUB_EVENT_NAME:-}",
  "ref": "${GITHUB_REF:-}",
  "sha": "${GITHUB_SHA:-}",
  "actor": "${GITHUB_ACTOR:-}",
  "runner_os": "${RUNNER_OS:-}",
  "runner_arch": "${RUNNER_ARCH:-}"
}
EOF

# Agent.

echo "Creating github agent"

AGENT_INFO=$("$INSTPATH/garnetctl" create agent \
	--version "$VERSION" \
	--ip "$RUNNER_IP" \
	--hostname "$HOSTNAME" \
	--machine-id "$MACHINE_ID" \
	--kind github \
	--context-file "$TMP_DIR/github-context.json") || fail $? "Failed to create agent"

AGENT_ID=$(echo "$AGENT_INFO" | jq -r '.id' 2>/dev/null)
AGENT_TOKEN=$(echo "$AGENT_INFO" | jq -r '.agent_token')

echo "Created agent with ID: $AGENT_ID"
export AGENT_TOKEN

# Network Policy.

echo "Getting network policy"

REPO_ID="${GITHUB_REPOSITORY:-}"
WORKFLOW="${GITHUB_WORKFLOW:-}"

NETPOLICY_PATH="$TMP_DIR/netpolicy.yaml"

echo "Fetching network policy for $REPO_ID/$WORKFLOW..."

"$INSTPATH/garnetctl" get network-policy merged \
	--repository-id "$REPO_ID" \
	--workflow-name "$WORKFLOW" \
	--format yaml \
	--output "$NETPOLICY_PATH" || fail $? "Failed to fetch network policy"

if [ ! -f "$NETPOLICY_PATH" ]; then
	fail 1 "Network policy file was not created"
fi

echo "Network policy saved to $NETPOLICY_PATH"
head -n 20 "$NETPOLICY_PATH" || true

echo "Installing obtained network policy to /etc/jibril/netpolicy.yaml"

#### Jibril runtime setup.

export GARNET_AGENT_TOKEN="$AGENT_TOKEN"
export GARNET_URL="$API"

echo "Creating Jibril default environment file"

AI_ENABLED=${AI_ENABLED:-"false"}
AI_MODE=${AI_MODE:-"reason"}
AI_TOKEN=${AI_TOKEN:-""}
AI_MODEL=${AI_MODEL:-"gpt-4o"}
AI_TEMPERATURE=${AI_TEMPERATURE:-"0.3"}
GARNET_SAR=${GARNET_SAR:-"true"}

cat >"$TMP_DIR/jibril.default" <<EOF
# Generated by scripts/action.sh
GARNET_AGENT_TOKEN=$GARNET_AGENT_TOKEN
GARNET_URL=$GARNET_URL
AI_ENABLED=$AI_ENABLED
AI_MODE=$AI_MODE
AI_TOKEN=$AI_TOKEN
AI_MODEL=$AI_MODEL
AI_TEMPERATURE=$AI_TEMPERATURE
GARNET_SAR=$GARNET_SAR
RUNNER_ARCH=${RUNNER_ARCH:-}
RUNNER_OS=${RUNNER_OS:-}
GITHUB_TOKEN=${GITHUB_TOKEN:-}
GITHUB_ACTOR=${GITHUB_ACTOR:-}
GITHUB_ACTOR_ID=${GITHUB_ACTOR_ID:-}
GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME:-}
GITHUB_JOB=${GITHUB_JOB:-}
GITHUB_REF=${GITHUB_REF:-}
GITHUB_REF_NAME=${GITHUB_REF_NAME:-}
GITHUB_REF_PROTECTED=${GITHUB_REF_PROTECTED:-}
GITHUB_REF_TYPE=${GITHUB_REF_TYPE:-}
GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-}
GITHUB_REPOSITORY_ID=${GITHUB_REPOSITORY_ID:-}
GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER:-}
GITHUB_REPOSITORY_OWNER_ID=${GITHUB_REPOSITORY_OWNER_ID:-}
GITHUB_RUN_ATTEMPT=${GITHUB_RUN_ATTEMPT:-}
GITHUB_RUN_ID=${GITHUB_RUN_ID:-}
GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER:-}
GITHUB_SERVER_URL=${GITHUB_SERVER_URL:-}
GITHUB_SHA=${GITHUB_SHA:-}
GITHUB_TRIGGERING_ACTOR=${GITHUB_TRIGGERING_ACTOR:-}
GITHUB_WORKFLOW=${GITHUB_WORKFLOW:-}
GITHUB_WORKFLOW_REF=${GITHUB_WORKFLOW_REF:-}
GITHUB_WORKFLOW_SHA=${GITHUB_WORKFLOW_SHA:-}
GITHUB_WORKSPACE=${GITHUB_WORKSPACE:-}
EOF

echo "Installing default environment file to /etc/default/jibril"
sudo -E install -D -o root -m 644 "$TMP_DIR/jibril.default" /etc/default/jibril

echo "Installing Jibril as a systemd service"
sudo -E $INSTPATH/jibril --systemd install

echo "Listing installed Jibril files:"
sudo find /etc/jibril/ || echo "No files found in /etc/jibril/"

# Verify configuration.
echo "Jibril configuration:"
sudo cat /etc/jibril/config.yaml || echo "No configuration file found"

# Configure logging.
echo "StandardError=append:/var/log/jibril.err" | sudo tee -a /etc/systemd/system/jibril.service
echo "StandardOutput=append:/var/log/jibril.log" | sudo tee -a /etc/systemd/system/jibril.service

echo "Jibril network policy:"
sudo head -n 20 /etc/jibril/netpolicy.yaml || echo "No network policy file found"

# Replace network policy with fetched one.
sudo cp -v "$NETPOLICY_PATH" /etc/jibril/netpolicy.yaml

echo "New Jibril network policy:"
sudo head -n 20 /etc/jibril/netpolicy.yaml || echo "No network policy file found"

echo "Reloading systemd and enabling Jibril service:"
sudo -E systemctl daemon-reload
sudo -E systemctl enable jibril.service || true

echo "Starting Jibril service:"
sudo -E systemctl start jibril.service || sudo journalctl -xeu jibril.service

sleep 5

echo "Checking Jibril service status:"
sudo -E systemctl status jibril.service --no-pager
