name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  copilot-setup-steps:        # name MUST be exactly this
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6      
      - uses: garnet-org/action@9205ed7fe6ee6006124b802bbf055387957151dd
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
