name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  copilot-setup-steps:        # name MUST be exactly this
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7      
      - uses: garnet-org/action@f54d7f914c5290c3d09b22d76249002013d730d2
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
