name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  copilot-setup-steps:        # name MUST be exactly this
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7      
      - uses: garnet-org/action@2f84b93b3fb06e7629e737f4487bda2d3ef1c551
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
