name: Smoke C

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  smoke-c:
    name: Smoke C
    uses: ./.github/workflows/reusable-smoke-test.yaml
    with:
      job_name: smoke-c
    secrets: inherit
