name: Garnet Security Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  garnet-scan:
    name: Garnet Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Garnet Security Scanner
        uses: garnet-org/action@main
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
          # Optional: Uncomment to customize API URL
          # api_url: https://api.garnet.ai
          debug: true