name: Test GarnetAI Action

on:
  workflow_dispatch:
    inputs:
      api_token:
        description: 'API token for GarnetAI service'
        required: true
      api_url:
        description: 'API URL for GarnetAI service'
        required: false
        default: 'https://api.garnet.ai'
      policy_path:
        description: 'Path to save the network policy file'
        required: false
        default: './config/netpolicy.yaml'
      garnetctl_version:
        description: 'Version of garnetctl CLI to download (without v prefix)'
        required: false
        default: 'latest'
      jibril_version:
        description: 'Jibril version for the daemon (without v prefix)'
        required: false
        default: '0.0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run GarnetAI Action
        uses: ./
        with:
          api_token: ${{ inputs.api_token }}
          api_url: ${{ inputs.api_url }}
          policy_path: ${{ inputs.policy_path }}
          garnetctl_version: ${{ inputs.garnetctl_version }}
          jibril_version: ${{ inputs.jibril_version }}